### ISSUE TITLE
[BUG] Numbers Incorrectly Cast As Strings

### ISSUE THREAD

**Issue by 7RedViolin** [7RedViolin/pySigma-backend-cortexxdr#1]
When using the sigma rule
```
title: Test Rule for System Process
status: test
logsource:
    category: process_creation
detection:
    sel:
        ProcessId: 4
    condition: sel
```

the resulting query is `dataset=xdr_data | filter (event_type = ENUM.PROCESS and event_sub_type = ENUM.PROCESS_START) and (action_process_os_pid = "4")`

This then throws the error `Value 4 for operator = is invalid. expected number but received string`
